spring.application.name=partiumServiceSystem
# application.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/partiumService
spring.datasource.username=postgres
spring.datasource.password=5418102
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
